production:
    resources:
        db:
          adapter: pdo_mysql
          params:
              dbname: ssk
              host: localhost
              username: root
              password:
              isDefaultTableAdapter: true
              charset: utf8

staging:
    _extends: production

testing:
    _extends: production

development:
    _extends: production