<?php
return array(
    'HelperAnotherPages',
    'HelperArticles',
    'HelperBanners',
    'HelperCatalogue',
    'HelperClients',
    'HelperFaq',
    'HelperFileTypes',
    'HelperGallery',
    'HelperLanguages',
    'HelperProjects',
    'HelperNews',
    'HelperSearch',
    'HelperSitemap',
    'HelperSystemTextes',
    'HelperVideogallery',
    'HelperVopros',
);